services:
  database:
    image: postgres:17.4-alpine3.21
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./backend:/var/www/html/backend
      - /var/www/html/backend/vendor
      - /var/www/html/backend/node_modules
    build:
      dockerfile: Laravel.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    volumes:
      - ./frontend:/var/www/html/frontend
      - /var/www/html/frontend/node_modules
    build:
      dockerfile: Next.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
