services:
  backend:
    volumes:
      - .:/var/www/html
    build:
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8000:8000
      - 5173:5173
    depends_on:
      - database
  database:
    image: postgres:17.4-alpine3.21
    env_file:
      - .env
    ports:
      - 5432:5432

