services:
  backend:
    volumes:
      - ..:/var/www/html
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres:17.4-alpine3.21
    env_file:
      - ../.env
    ports:
      - 5432:5432

